puts "Entrer un nombrethen "
case gets.to_i
  when 1 then puts "un"
  when 2 then puts "deux"
  when 3 then puts "trois"
  when 4 then puts "quatre"
  when 5 then puts "cinq"
  when 6 then puts "six"
  when 7 then puts "sept"
  when 8 then puts "huit"
  when 9 then puts "neuf"
  else "On vous a demandé un chiffre non?"
